name: Release

on:
  push:
    tags:
      - 'v*.*.*'       # e.g., v1.0.0, v0.1.0
      - 'v*.*.*a*'     # e.g., v0.1.0a1 (alpha)
      - 'v*.*.*b*'     # e.g., v0.1.0b1 (beta)
      - 'v*.*.*rc*'    # e.g., v0.1.0rc1 (release candidate)

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Extract version from tag
      id: version
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Update version in pyproject.toml
      run: |
        sed -i 's/version = ".*"/version = "${{ steps.version.outputs.VERSION }}"/' pyproject.toml
        git diff pyproject.toml

    - name: Build package
      run: |
        python -m build

    - name: Check package
      run: |
        python -m twine check dist/*

    - name: Generate changelog
      id: changelog
      run: |
        # Simple changelog generation (you can enhance this)
        echo "## Changes in ${{ steps.version.outputs.TAG }}" > RELEASE_CHANGELOG.md
        echo "" >> RELEASE_CHANGELOG.md
        echo "### What's New" >> RELEASE_CHANGELOG.md

        # Get commits since last tag
        if git describe --tags --abbrev=0 HEAD~1 2>/dev/null; then
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD~1)
          git log --pretty=format:"- %s" $LAST_TAG..HEAD >> RELEASE_CHANGELOG.md
        else
          git log --pretty=format:"- %s" HEAD~10..HEAD >> RELEASE_CHANGELOG.md
        fi

        echo "" >> RELEASE_CHANGELOG.md
        echo "### Installation" >> RELEASE_CHANGELOG.md
        echo '```bash' >> RELEASE_CHANGELOG.md
        echo 'pip install brokle==${{ steps.version.outputs.VERSION }}' >> RELEASE_CHANGELOG.md
        echo '```' >> RELEASE_CHANGELOG.md

    - name: Determine if pre-release
      id: prerelease
      run: |
        if [[ "${{ steps.version.outputs.VERSION }}" =~ (a|b|rc) ]]; then
          echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
          echo "RELEASE_NAME=Pre-release ${{ steps.version.outputs.TAG }}" >> $GITHUB_OUTPUT
        else
          echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
          echo "RELEASE_NAME=Release ${{ steps.version.outputs.TAG }}" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.TAG }}
        release_name: ${{ steps.prerelease.outputs.RELEASE_NAME }}
        body_path: RELEASE_CHANGELOG.md
        draft: false
        prerelease: ${{ steps.prerelease.outputs.IS_PRERELEASE }}

    - name: Upload wheel to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/brokle-${{ steps.version.outputs.VERSION }}-py3-none-any.whl
        asset_name: brokle-${{ steps.version.outputs.VERSION }}-py3-none-any.whl
        asset_content_type: application/zip

    - name: Upload source to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/brokle-${{ steps.version.outputs.VERSION }}.tar.gz
        asset_name: brokle-${{ steps.version.outputs.VERSION }}.tar.gz
        asset_content_type: application/gzip

  publish-to-pypi:
    name: Publish to PyPI
    needs: create-release
    runs-on: ubuntu-latest
    environment: pypi

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Extract version from tag
      id: version
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Update version in pyproject.toml
      run: |
        sed -i 's/version = ".*"/version = "${{ steps.version.outputs.VERSION }}"/' pyproject.toml

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/* --verbose